# Main Hyprland Config

# Load Variables and Programs first
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/environments.conf

# Load Hardware/Monitor settings
source = ~/.config/hypr/conf/monitors.conf

# Load Visuals and Input
source = ~/.config/hypr/conf/appearance.conf
# Note: You can also move the 'input' and 'gestures' blocks to a separate 'input.conf'
source = ~/.config/hypr/conf/input.conf

# Load Logic
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/keybindings.conf

# Run Apps
source = ~/.config/hypr/conf/autostart.conf

