wallpaper {
	monitor = # We leave it blank, and it'll be the fallback, that is all my monitors
	path = ~/Pictures/wallpapers/all_wallpapers # This is the path to my wallpapers. We'll figure out how to work with wallpapers when a theme is chosen a bit later on
	fit_mode = fill # can be contain, cover, tile, or fill
	timeout = 300 # Changes wallpapers after every 5 minutes
}
