-- Generated by Noctalia

local primary = "rgb(3daee9)"
local surface = "rgb(202224)"
local secondary = "rgb(1d99f3)"
local error = "rgb(da4453)"

hl.config({
	general = {
		col = {
			active_border = primary,
			inactive_border = surface,
		},
	},

	group = {
		col = {
			border_active = secondary,
			border_inactive = surface,
			border_locked_active = error,
			border_locked_inactive = surface,
		},

		groupbar = {
			col = {
				active = secondary,
				inactive = surface,
				locked_active = error,
				locked_inactive = surface,
			},
		},
	},
})
