#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:


exec-once = ~/.config/hypr/launch_waybar.sh
# Start the clipboard daemon
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

exec-once = ~/.config/hypr/sync_walls.sh && hyprpaper
exec-once = swaync
exec-once = hyprpaper
