# Dark mode environment variables
env = GTK_THEME,Adwaita:dark
env = GTK2_RC_FILES,/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc
env = QT_STYLE_OVERRIDE,Adwaita-Dark

# Blurring the waybar
blurls = waybar

