###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use

$terminal = kitty
$fileManager = yazi
$menu = anyrun
$browser = zen-browser
$launcher = rofi -show drun
$music = spotify
$changeWallpaper = ~/.config/hypr/change_wallpaper.sh
